### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [yehia-mamdouh/XSSYA#2]
I am a Developer for the ArchAssault Project, we woudl like to include this in our repo, but we noticed its missing a license. Can you please add a license file to it?

**Comment by yehia-mamdouh** [comment]
Dear MaxisolerI have Released XSSYA V-2.0 http://labs.dts-solution.com/xssya-forget-the-browser-for-…/For direct Download https://github.com/yehia-mamdouh/XSSYA-V-2.0

ThanksYehia Mamdouh
Date: Fri, 13 Jun 2014 05:10:53 -0700

**Comment by yehia-mamdouh** [comment]
Dear SirI have Released XSSYA V-2.0 http://labs.dts-solution.com/xssya-forget-the-browser-for-…/For direct Download https://github.com/yehia-mamdouh/XSSYA-V-2.0

ThanksYehia Mamdouh
From: yehiamamdouh51@hotmail.com
To: reply@reply.github.com
Subject: RE: [XSSYA] Distribution Request (#2)
Date: Tue, 10 Mar 2015 08:58:32 +0200




Dear MaxisolerI have Released XSSYA V-2.0 http://labs.dts-solution.com/xssya-forget-the-browser-for-…/For direct Download https://github.com/yehia-mamdouh/XSSYA-V-2.0

ThanksYehia Mamdouh
Date: Fri, 13 Jun 2014 05:10:53 -0700
