### ISSUE TITLE
Issue when attempting to run xssya: ImportError: No module named gdshortener

### ISSUE THREAD

**Issue by brandontict** [yehia-mamdouh/XSSYA#6]
When I try to run XSSYA, I receive the follow error , 

"ImportError: No module named gdshortener" 

There is not much material on gdshortner . 

I am running the latest version of Kali 

Here is full output: 

[r000t:/opt/XSSYA-V-2.0-master]# python xssya.py 
Traceback (most recent call last):
  File "xssya.py", line 19, in <module>
    import gdshortener
ImportError: No module named gdshortener

Looks like a great tool , would love to give it a try. 

Thanks

**Comment by yehia-mamdouh** [comment]
You need to download this modules colorama-0.2.7 
https://pypi.python.org/pypi/colorama gdshortener 0.0.2 
https://pypi.python.org/pypi/gdshortener

Beside i have released XSSYA V2 which have more features try it
https://github.com/yehia-mamdouh/XSSYA-V-2.0
