### ISSUE TITLE
Error in the script 

### ISSUE THREAD

**Issue by Ghostboy-287** [yehia-mamdouh/XSSYA#8]
root@root:~/hack/XSSYA# python xssya.py 

Traceback (most recent call last):
  File "xssya.py", line 67, in <module>
    class fake_ssl:
  File "xssya.py", line 68, in fake_ssl
    wrap_socket = partial(ssl.wrap_socket, ssl_version=ssl.PROTOCOL_SSLv3)
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by NetSec144** [comment]
Was there any results to this issue?
I'm running it in Kali 2016.2 with the same issue.

**Comment by yehia-mamdouh** [comment]
remove the fake_ssl calss from the script
class fake_ssl:
    wrap_socket = partial(ssl.wrap_socket, ssl_version=ssl.PROTOCOL_TLSv1)
httplib.ssl = fake_ssl
remove those lines and it will work

**Comment by Ghostboy-287** [comment]
thank you very much , we appreciate your works :)
